[profile.default]
via_ir = false
src = 'contracts'
cache_path = 'cache_forge'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
script = 'forge-scripts'
evm_version = 'shanghai'

optimizer_runs = 15000

[fuzz]
runs = 1000
max_test_rejects = 1000000

[profile.optimized]
solc = '0.8.10'

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
polygonzk = "${POLYGON_ZK_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
unknown_chain = { key = "${TENDERLY_ACCESS_TOKEN}", chain = 12345, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}" }
